version: '3'
services:
  pet-backend:
    image: pet-backend:latest
    ports:
      - "8080:8080"
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.4

  pet-front:
    image: pet-front:latest
    ports:
      - "8000:80"
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.5

  jenkins:
    image: custom-jenkins-docker
    ports:
      - "8081:8080"
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.2
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

#selenium
  selenium-hub:
    image: selenium/hub:4.13.0-20231004
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.10

  chrome:
    image: selenium/node-chrome:4.13.0-20231004
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5900:5900"  # Adiciona a porta 5900 para VNC
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.11

  edge:
    image: selenium/node-edge:4.13.0-20231004
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.12

  firefox:
    image: selenium/node-firefox:4.13.0-20231004
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.13
        
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.14
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=actualdb

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      sinteticos-network:
        ipv4_address: 172.168.0.15
    volumes:
      - grafana-storage:/var/lib/grafana
    
volumes:
  jenkins-data:
    external: true
  influxdb-storage:
    external: true
  grafana-storage:
    external: true
  
networks:
  sinteticos-network:
    ipam:
      driver: default
      config:
        - subnet: 172.168.0.0/16
